---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterName }}-datadog-secret
  namespace: {{ .Values.namespace }}
spec:
  target:
    name: datadog-secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: {{ .Values.secretVaultPath }}
---
apiVersion: v1
kind: Service
metadata:
  name: datadog-apm
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: datadog
  ports:
    - protocol: TCP
      port: 8126
      targetPort: 8126
