apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 120s
  secretStoreRef:
    kind: ClusterSecretStore
    name: konstruct-aws-ssm
  target:
    name: github-app-credentials
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          managed-by: argocd.argoproj.io
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        # Template will be populated from Vault data
        type: "{{ .type }}"
        url: "{{ .url }}"
        app_id: "{{ .githubAppID }}"
        installation_id: "{{ .githubAppInstallationID }}"
        github_app_private_key: "{{ .githubAppPrivateKey }}"
  dataFrom:
    - extract:
        key: /argocd/repo-credentials-template/{{ .Values.projectName }}
