{{- if or (eq .Values.externalDns.providerName "cloudflare") (eq .Values.externalDns.providerName "civo") }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-secrets
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    name: external-dns-secrets
    creationPolicy: Owner
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ include "controlplane.secretStoreName" . }}
  refreshInterval: 1h
  data:
    - remoteRef:
        {{- if eq .Values.externalDns.providerName "civo" }}
        key: {{ include "controlplane.secretKey" (dict "Values" .Values "key" "konstruct/civo") }}
        {{- else }}
        key: {{ include "controlplane.secretKey" (dict "Values" .Values "key" "konstruct/cloudflare") }}
        {{- end }}
        property: token
      secretKey: token
{{- end }}
