{{- if eq .Values.cloudProvider "civo" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: {{ default "0.25.0" .Values.versions.vault | quote }}
    helm:
      values: |-
        server:
          affinity: ""
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true
              setNodeId: true
              config: |
                ui = true
                listener "tcp" {
                  tls_disable     = 1
                  address         = "[::]:8200"
                  cluster_address = "[::]:8201"
                }
                storage "raft" {
                  path = "/vault/data"
                }
                service_registration "kubernetes" {}
          ui:
            enabled: true
            serviceType: ClusterIP
            serviceNodePort: null
            externalPort: 8200
  destination:
    name: in-cluster
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
