apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.workloadAccountId }}:role/eso-{{ .Values.projectClusterName }}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-private
  namespace: argocd
spec:
  region: {{ .Values.aws.workloadRegion }}
  scope: private
  auth:
    jwt:
      serviceAccountRef:
        name: external-secrets
