apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atlantis-vcs
  namespace: atlantis
  annotations:
    argocd.argoproj.io/sync-wave: "49"
spec:
  target:
    name: atlantis-vcs
    template:
      engineVersion: v2
      data:
        ATLANTIS_GH_APP_ID: {{`"{{ .githubAppID }}"`}}
        ATLANTIS_GH_APP_INSTALLATION_ID: {{`"{{ .githubAppInstallationID }}"`}}
        ATLANTIS_GH_APP_KEY: {{`"{{ .githubAppPrivateKey }}"`}}
        ATLANTIS_GH_WEBHOOK_SECRET: {{`"{{ .atlantisWebhookSecret }}"`}}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.workloadClusterName }}-vault-kv-secret
  data:
  - remoteRef:
      key: argocd/repo-credentials-template/{{ .Values.workloadClusterProjectName }}
      property: githubAppID
    secretKey: githubAppID
  - remoteRef:
      key: argocd/repo-credentials-template/{{ .Values.workloadClusterProjectName }}
      property: githubAppInstallationID
    secretKey: githubAppInstallationID
  - remoteRef:
      key: argocd/repo-credentials-template/{{ .Values.workloadClusterProjectName }}
      property: githubAppPrivateKey
    secretKey: githubAppPrivateKey
  - remoteRef:
      key: argocd/repo-credentials-template/{{ .Values.workloadClusterProjectName }}
      property: atlantisWebhookSecret
    secretKey: atlantisWebhookSecret
