apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum-components
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '50'
spec:
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.gitopsRepoUrl }}
    path: registry/clusters/{{ .Values.clusterName }}/components/chartmuseum
    targetRevision: HEAD
  destination:
    name: {{ .Values.clusterDestination }}
    namespace: chartmuseum
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
