apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.workloadClusterName }}-external-dns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: {{ .Values.workloadClusterName }}
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.20.0
    helm:
      releaseName: external-dns
      values: |
        serviceAccount:
          create: true
          name: external-dns
        provider: {{ .Values.externalDnsProviderName }}
        sources:
          - service
          - gateway-httproute
          - gateway-tlsroute
          - gateway-tcproute
          - gateway-udproute
        domainFilters:
        - {{ .Values.domainName }}
        env:
        - name: {{ .Values.externalDnsProviderTokenEnvName }}
          valueFrom:
            secretKeyRef:
              name: external-dns-secrets
              key: token
    chart: external-dns
  destination:
    name: {{ .Values.workloadClusterName }}
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-gateway
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways", "httproutes", "grpcroutes", "tlsroutes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-gateway
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: external-dns
