apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.workloadClusterName }}-ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: {{ .Values.workloadClusterName }}
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.1
    helm:
      values: |-
        controller:
          ingressClass: nginx
          publishService:
            enabled: true
          extraArgs:
            enable-ssl-passthrough: true
    chart: ingress-nginx
  destination:
    name: {{ .Values.workloadClusterName }}
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
