workloadClusterTerraformModuleUrl: "git::https://github.com/konstruct-saas/gitops.git//terraform/civo/modules/project-cluster?ref=main"

# @input.type: string
# @input.description: Alert email address for cert-manager notifications
# @input.required: false
email: 123@gmail.com

domainName: konstruct.io

# Wait Job Configuration
waitJobImage: "dtzar/helm-kubectl:3.19.0"
