apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

# To upgrade ArgoCD, increment the version here
# https://github.com/argoproj/argo-cd/tags
resources:
  - github.com:konstructio/manifests.git/argocd/cloud?ref=jokestax-patch-2
{{- if not .Values.saas }}
  - argocd-ui-httproute.yaml
{{- end }}
  - application.yaml
  - rbac.yaml
  - git-token-refresher.yaml
{{- if and (eq .Values.gitProvider "gitlab") (not .Values.saas) }}
  - git-token-app.yaml
{{- end }}
  
patchesStrategicMerge:
  - argocd-cm.yaml
  - argocd-cmd-params-cm.yaml
  - argocd-server-sa.yaml
  - argocd-application-controller-sa.yaml
  - argocd-applicationset-controller-sa.yaml
  - argocd-server-deployment.yaml
  - argocd-application-controller-statefulset.yaml
  - argocd-repo-server-deployment.yaml

generatorOptions:
  disableNameSuffixHash: true
