apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.modelCachePvcName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.modelCacheSize }}
  storageClassName: {{ .Values.storageClassName }}
