apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: 'https://argocd-{{ .Values.projectClusterName }}.{{ .Values.domainName }}'
  oidc.config: |
    name: Dex
    issuer: {{ .Values.dexDomainName }}
    clientID: argocd
    clientSecret: app-secret
    requestedScopes:
    - openid
    - profile
    - email
    - groups
