apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.workloadClusterName }}-theme
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '45'
spec:
  project: default
  source:
    repoURL: {{ .Values.gitopsRepoUrl }}
    path: registry/clusters/{{ .Values.workloadClusterName }}/theme
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: theme
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
