---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterName }}-oauth2proxy-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '40'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secretStoreName }}
  target:
    name: oauth2proxy-oauth2-proxy
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: {{ .Values.secretPath }}
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: {{ .Values.secretPath }}
        property: client-secret
    - secretKey: cookie-secret
      remoteRef:
        key: {{ .Values.secretPath }}
        property: cookie-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterName }}-oauth2proxy-redis-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '40'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secretStoreName }}
  target:
    name: oauth2proxy-redis-secret
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: {{ .Values.secretPath }}
        property: redis-password
