apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-config
  namespace: dex
spec:
  target:
    name: dex-config
    template:
      type: Opaque
      engineVersion: v2
      data:
        config.yaml: |
          issuer: https://dex.{{ .Values.domainName }}
          logger:
            level: "info"
            format: "json"
          storage:
            type: kubernetes
            config:
              inCluster: true
          web:
            http: 0.0.0.0:5556
            skipApprovalScreen: true
            allowedOrigins:
              - "http://localhost:5555"
              - "http://127.0.0.1:5555"
              - "https://konstruct.{{ .Values.domainName }}"
          grpc:
            addr: 0.0.0.0:5557
          telemetry:
            http: 0.0.0.0:5558
          oauth2:
            skipApprovalScreen: true
            passwordConnector: local
          enablePasswordDB: true
          staticPasswords:
          - email: "kbot"
            hash: {{ "{{ .ADMIN_PASSWORD }}" }}
            username: "admin"
            userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
            displayName: "kbot"
            givenName: "kbot"
            familyName: "User"
          staticClients:
          {{`{{- $clients := .STATIC_CLIENTS_JSON | fromJson }}`}}
          {{`{{- range $clients }}`}}
            - id: {{`{{ .id }}`}}
              name: {{`{{ .name }}`}}
              redirectURIs:
              {{`{{- range .redirectURIs }}`}}
                - {{`{{ . }}`}}
              {{`{{- end }}`}}
              secret: {{`{{ .secret }}`}}
              public: {{`{{ .public }}`}}
              {{`{{- if .trustedPeers }}`}}
              trustedPeers:
              {{`{{- range .trustedPeers }}`}}
                - {{`{{ . }}`}}
              {{`{{- end }}`}}
              {{`{{- end }}`}}
          {{`{{- end }}`}}
  secretStoreRef:
    kind: ClusterSecretStore
    name: konstruct-aws-ssm
  refreshInterval: 10s
  data:
    - secretKey: STATIC_CLIENTS_JSON
      remoteRef:
        key: /konstruct/dex
        property: STATIC_CLIENTS_JSON
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: /konstruct/dex
        property: ADMIN_PASSWORD
