apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: controller-manager
  namespace: github-runner
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    name: controller-manager
  secretStoreRef:
    kind: ClusterSecretStore
    name: konstruct-aws-ssm
  data:
    - remoteRef:
        key: /argocd/repo-credentials-template/{{ .Values.projectName }}
        property: githubAppID
      secretKey: github_app_id
    - remoteRef:
        key: /argocd/repo-credentials-template/{{ .Values.projectName }}
        property: githubAppPrivateKey
      secretKey: github_app_private_key
    - remoteRef:
        key: /argocd/repo-credentials-template/{{ .Values.projectName }}
        property: githubAppInstallationID
      secretKey: github_app_installation_id
