apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: controller-manager
  namespace: github-runner
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    name: controller-manager
  secretStoreRef:
    kind: ClusterSecretStore
    name: konstruct-aws-ssm
  data:
    - remoteRef:
        key: /konstruct/konstruct-api
        property: GITHUB_APP_ID
      secretKey: github_app_id
    - remoteRef:
        key: /konstruct/konstruct-api
        property: GITHUB_APP_PRIVATE_KEY
      secretKey: github_app_private_key
    - remoteRef:
        key: /konstruct/konstruct-api
        property: GITHUB_APP_INSTALLATION_ID
      secretKey: github_app_installation_id
