apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: {{ .Values.workloadClusterName }}-infrastructure
spec:
  providerConfigRef: 
    name: {{ .Values.workloadClusterName }}
  forProvider:
    source: Remote
    module: {{ .Values.workloadClusterTerraformModuleUrl }}
    enableTerraformCLILogging: true
    vars:
    - key: cluster_name
      value: "{{ .Values.workloadClusterName }}"
    - key: cluster_region
      value: "{{ .Values.workloadClusterRegion }}"
    - key: node_count
      value: "{{ .Values.workloadNodeCount }}"
    - key: node_type
      value: "{{ .Values.workloadNodeType }}"
    - key: ami_type
      value: "{{ .Values.workloadAmiType }}"
    - key: s3_bucket_name
      value: "{{ .Values.workloadS3BucketName }}"
    - key: account_id
      value: "{{ .Values.workloadClusterAccountId }}"
    - key: kubefirst_mgmt_cluster_name
      value: "{{ .Values.kubefirstMgmtClusterName }}"
