apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: <WORKLOAD_CLUSTER_NAME>
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: <WORKLOAD_CLUSTER_NAME> description
  sourceNamespaces: ["<WORKLOAD_CLUSTER_NAME>-environment"]
  sourceRepos:
  - '<TEAM_GITOPS_REPO_URL>'
  destinations:
  - name: <WORKLOAD_CLUSTER_NAME>
    namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - description: <WORKLOAD_CLUSTER_NAME>-admin-role
    groups:
    - admins
    name: admin-role
    policies:
    - p, proj:<WORKLOAD_CLUSTER_NAME>:admin-role, applications, *, <WORKLOAD_CLUSTER_NAME>/*, allow
