apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.clusterName }}-runai
  namespace: argocd
  annotations:
    kubefirst.konstruct.io/application-name: runai
    kubefirst.konstruct.io/source: catalog-templates
    argocd.argoproj.io/sync-wave: '50'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace }}
    name: {{ .Values.clusterDestination }}
  project: {{ .Values.project }}
  source:
    repoURL: https://run-ai-charts.storage.googleapis.com
    chart: runai-cluster
    targetRevision: {{ .Values.chartVersion }}
    helm:
      releaseName: runai-cluster
      values: |
        cluster:
          url: {{ .Values.clusterUrl }}
          uid: {{ .Values.clusterUid }}
          name: {{ .Values.clusterName }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
