apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runai-prereqs-{{ .Values.clusterName }}
  namespace: {{ .Values.argocdAppNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "49"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: {{ .Values.clusterDestination }}
    namespace: runai
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.gitopsRepoUrl }}
    path: registry/environments/runai/{{ .Values.clusterName }}/prereqs
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
