apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.clusterName }}-groundcover
  namespace: argocd
  annotations:
    kubefirst.konstruct.io/application-name: groundcover
    kubefirst.konstruct.io/source: catalog-templates
    argocd.argoproj.io/sync-wave: '10'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace }}
    name: {{ .Values.clusterDestination }}
  project: {{ .Values.project }}
  source:
    chart: groundcover
    repoURL: https://helm.groundcover.com
    targetRevision: {{ .Values.chartVersion }}
    helm:
      releaseName: groundcover
      valuesObject:
        victoria-metrics-operator:
          enabled: true
          builtinVMAgent:
            enabled: true
            spec:
              remoteWrite:
                - url: https://{{ .Values.ingestEndpoint }}/api/v1/write
                  headers:
                    - "apikey:%{API_KEY}"
        global:
          groundcoverPredefinedTokenSecret:
            secretName: groundcover-token
            secretKey: ingestion-key
          datadogapm:
            overrideUrl: https://{{ .Values.ingestEndpoint }}
          ingress:
            site: {{ .Values.ingestEndpoint }}
          logs:
            overrideUrl: https://{{ .Values.ingestEndpoint }}/loki/api/v1/push
          backend:
            enabled: false
          telemetry:
            enabled: false
          metrics:
            overrideUrl: https://{{ .Values.ingestEndpoint }}
          vector:
            logs:
              otlp:
                overrideHttpURL: https://{{ .Values.ingestEndpoint }}
        clusterId: {{ .Values.clusterDisplayName }}
        custom-metrics:
          extraArgs:
            remoteWrite.url: https://{{ .Values.ingestEndpoint }}/api/v1/write
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
