---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterName }}-groundcover-token
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    name: groundcover-token
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secretStoreName }}
  refreshInterval: 10s
  data:
    - secretKey: ingestion-key
      remoteRef:
        key: {{ .Values.secretPath }}
        property: ingestion-key
