apiVersion: v2
name: dynamo-platform
description: A Helm chart for deploying the NVIDIA AI Dynamo Platform (dynamo-operator + supporting subcharts) with ArgoCD
type: application
version: 0.1.0
appVersion: "1.0.2"
