{{- if eq .Values.awsSsmStoreKind "SecretStore" }}
{{- range .Values.awsSsmStoreNamespaces }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ $.Values.workloadClusterName }}-aws-ssm
  namespace: {{ . }}
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ $.Values.workloadClusterRegion }}
---
{{- end }}
{{- else }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.workloadClusterName }}-aws-ssm
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.workloadClusterRegion }}
{{- end }}
