apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-toolkit-arc-<WORKLOAD_CLUSTER_NAME>
  namespace: github-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-toolkit-arc-<WORKLOAD_CLUSTER_NAME>
  namespace: github-runner
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-toolkit-arc-<WORKLOAD_CLUSTER_NAME>
  namespace: github-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-toolkit-arc-<WORKLOAD_CLUSTER_NAME>
subjects:
  - kind: ServiceAccount
    name: k8s-toolkit-arc-<WORKLOAD_CLUSTER_NAME>
    namespace: github-runner
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '51'
  name: wait-actions-runner-controller-<WORKLOAD_CLUSTER_NAME>
  namespace: github-runner
spec:
  template:
    spec:
      containers:
        - args:
            - wait-for
            - deployment
            - --namespace
            - github-runner
            - --label
            - app.kubernetes.io/name=actions-runner-controller
          image: ghcr.io/konstructio/kubernetes-toolkit:v0.1.3
          imagePullPolicy: IfNotPresent
          name: wait
      restartPolicy: OnFailure
      serviceAccountName: k8s-toolkit-arc-<WORKLOAD_CLUSTER_NAME>
