apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: {{ .Values.workloadClusterName }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.project.awsAccountId }}:role/eso-{{ .Values.workloadClusterName }}-one
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-private
  namespace: {{ .Values.workloadClusterName }}
spec:
  region: {{ .Values.project.region }}
  role: arn:aws:iam::{{ .Values.project.awsAccountId }}:role/eso-{{ .Values.workloadClusterName }}-one
  scope: private
  auth:
    jwt:
      serviceAccountRef:
        name: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ecr-auth
  namespace: {{ .Values.workloadClusterName }}
spec:
  refreshInterval: "1h"
  target:
    name: ecr-auth
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          expiresAt: "{{ "{{ .expires_at }}" }}"
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ "{{ .proxy_endpoint | replace \"https://\" \"\" }}" }}": {
                "username": "{{ "{{ .username }}" }}",
                "password": "{{ "{{ .password }}" }}",
                "auth": "{{ "{{ printf \"%s:%s\" .username .password | b64enc }}" }}"
              }
            }
          }
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: ecr-private
