apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<WORKLOAD_CLUSTER_ACCOUNT_ID>:role/eso-<WORKLOAD_CLUSTER_NAME>
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-private
  namespace: argocd
spec:
  region: <WORKLOAD_CLUSTER_REGION>
  scope: private
  auth:
    jwt:
      serviceAccountRef:
        name: external-secrets
