apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  target:
    name: github-app-credentials
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          managed-by: argocd.argoproj.io
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        type: "git"
        url: {{ .Values.gitopsRepoUrl }}
        app_id: "{{ .githubAppID }}"
        installation_id: "{{ .githubAppInstallationID }}"
        github_app_private_key: "{{ .githubAppPrivateKey }}"
  secretStoreRef:
    kind: ClusterSecretStore
    name: konstruct-aws-ssm
  refreshInterval: 10s
  data:
    - remoteRef:
        key: /konstruct/konstruct-api
        property: GITHUB_APP_ID
      secretKey: githubAppID
    - remoteRef:
        key: /konstruct/konstruct-api
        property: GITHUB_APP_PRIVATE_KEY
      secretKey: githubAppPrivateKey
    - remoteRef:
        key: /konstruct/konstruct-api
        property: GITHUB_APP_INSTALLATION_ID
      secretKey: githubAppInstallationID
