apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crossplane-secrets
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ include "controlplane.secretStoreName" . }}
  target:
    name: crossplane-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ include "controlplane.secretKey" (dict "Values" .Values "key" "crossplane") }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-credentials
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ include "controlplane.secretStoreName" . }}
  target:
    name: git-credentials
    template:
      engineVersion: v2
      data:
        creds: |
          https://{{ "{{ .username }}" }}:{{ "{{ .password }}" }}@{{ (urlParse .Values.gitopsRepoUrl).host }}
  data:
    - secretKey: username
      remoteRef:
        key: {{ include "controlplane.secretKey" (dict "Values" .Values "key" "crossplane") }}
        property: username
        conversionStrategy: Default
    - secretKey: password
      remoteRef:
        key: {{ include "controlplane.secretKey" (dict "Values" .Values "key" "crossplane") }}
        property: password
        conversionStrategy: Default
{{- if eq .Values.cloudProvider "civo" }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: civo-creds
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ include "controlplane.secretStoreName" . }}
  target:
    name: civo-creds
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        config.json: |
          {
            "apikeys": {
              "tf_key": "{{ "{{ .civoToken }}" }}"
            },
            "meta": {
              "current_apikey": "tf_key"
            }
          }
  data:
    - secretKey: civoToken
      remoteRef:
        key: {{ include "controlplane.secretKey" (dict "Values" .Values "key" "crossplane") }}
        property: token
{{- end }}
