apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crossplane-secrets
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ include "controlplane.secretStoreName" . }}
  target:
    name: crossplane-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ include "controlplane.secretKey" (dict "Values" .Values "key" "crossplane") }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-credentials
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ include "controlplane.secretStoreName" . }}
  target:
    name: git-credentials
    template:
      engineVersion: v2
      data:
        creds: |
          https://{{ "{{ .username }}" }}:{{ "{{ .password }}" }}@{{ (urlParse .Values.gitopsRepoUrl).host }}
  data:
    - secretKey: username
      remoteRef:
        key: {{ include "controlplane.secretKey" (dict "Values" .Values "key" (printf "argocd/repo-credentials-template/%s" .Values.projectName)) }}
        property: username
        conversionStrategy: Default
    - secretKey: password
      remoteRef:
        key: {{ include "controlplane.secretKey" (dict "Values" .Values "key" (printf "argocd/repo-credentials-template/%s" .Values.projectName)) }}
        property: password
        conversionStrategy: Default
