apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: konstruct-clusters
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: {{ .Values.clusterDestination }}
  project: {{ .Values.project }}
  source:
    path: registry/clusters/{{ .Values.clusterName }}/components/konstruct-clusters
    repoURL: '{{ .Values.gitopsRepoUrl }}'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
