apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountId }}:role/konstruct-argocd-{{ .Values.clusterName }}
  name: argocd-application-controller
  namespace: argocd
