apiVersion: v1
kind: ServiceAccount
metadata:
{{- if eq .Values.cloudProvider "aws" }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountId }}:role/konstruct-argocd-{{ .Values.clusterName }}
{{- end }}
  name: argocd-server
  namespace: argocd
