apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: crossplane-secrets
  namespace: crossplane-system
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: /crossplane
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: <WORKLOAD_CLUSTER_NAME>-vault-kv-secret
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: crossplane-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 120s
  secretStoreRef:
    kind: ClusterSecretStore
    name: <WORKLOAD_CLUSTER_NAME>-vault-kv-secret
  target:
    name: github-app-credentials
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          managed-by: argocd.argoproj.io
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        # Template will be populated from Vault data
        type: "{{ .type }}"
        url: "{{ .url }}"
        app_id: "{{ .githubAppID }}"
        installation_id: "{{ .githubAppInstallationID }}"
        github_app_private_key: "{{ .githubAppPrivateKey }}"
  dataFrom:
    - extract:
        key: argocd/repo-credentials-template/<PROJECT_NAME>-platform

