apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.projectClusterName }}-cluster-secret-store
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '35'
spec:
  project: {{ .Values.projectClusterName }}
  source:
    repoURL: {{ .Values.gitopsRepoUrl }}
    path: registry/konstruct-clusters/{{ .Values.projectClusterName }}/cluster-secret-store
    targetRevision: HEAD
  destination:
    name: {{ .Values.projectClusterName }}
    namespace: external-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
