apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ include "controlplane.secretStoreName" . }}
  annotations:
    argocd.argoproj.io/sync-wave: '40'
spec:
  provider:
{{- if eq .Values.secretStore.provider "vault" }}
    vault:
      server: {{ .Values.secretStore.vault.address | quote }}
      path: {{ default "secret" .Values.secretStore.vault.path | quote }}
      version: {{ default "v2" .Values.secretStore.vault.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ default "kubernetes/kubefirst" .Values.secretStore.vault.kubernetesAuthPath | quote }}
          role: {{ default "external-secrets" .Values.secretStore.vault.role | quote }}
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-operator
{{- else }}
    aws:
      service: ParameterStore
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-operator
{{- end }}
