apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.projectClusterName }}-vault-kv-secret
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  provider:
    vault:
      server: 'https://vault.{{ .Values.domainName }}'
      path: 'secret'
      version: 'v2'
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "{{ .Values.projectClusterName }}-cluster-vault-bootstrap"
          key: "vault-token"
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.projectClusterName }}-aws-ssm
spec:
  provider:
    aws:
      service: ParameterStore
      role: arn:aws:iam::{{ .Values.aws.workloadAccountId }}:role/eso-{{ .Values.projectClusterName }}
      region: {{ .Values.aws.workloadRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-operator
