{{- if eq .Values.externalDns.providerName "cloudflare" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-secrets
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    name: external-dns-secrets
    creationPolicy: Owner
  secretStoreRef:
    kind: ClusterSecretStore
    name: konstruct-aws-ssm
  refreshInterval: 1h
  data:
    - remoteRef:
        key: /konstruct/cloudflare
        property: token
      secretKey: token
{{- end }}
