apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-dns-secrets
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    name: external-dns-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  data:
    - remoteRef:
        key: external-dns
        property: token
      secretKey: token
