apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: {{ .Values.workloadClusterName }}-infrastructure
spec:
  providerConfigRef: 
    name: {{ .Values.workloadClusterName }}
  forProvider:
    source: Remote
    module: {{ .Values.workloadClusterTerraformModuleUrl }}
    vars:
    - key: cluster_name
      value: "{{ .Values.workloadClusterName }}"
    - key: cluster_region
      value: "{{ .Values.workloadClusterRegion }}"
    - key: node_count
      value: "{{ .Values.workloadNodeCount }}"
    - key: node_type
      value: "{{ .Values.workloadNodeType }}"
    - key: ami_type
      value: "{{ .Values.workloadAmiType }}"
    - key: project_aws_account_id
      value: "{{ .Values.projectAwsAccountId }}"
    - key: project_cluster_name
      value: "{{ .Values.projectClusterName }}"
    - key: dex_provider_name
      value: "{{ .Values.dexProviderName }}"
    # Empty skips the EKS OIDC identity provider config in the module.
    - key: dex_issuer_url
      value: "{{ .Values.dexIssuerUrl }}"


